### ISSUE TITLE
Angebot

### ISSUE THREAD

**Issue by LOX311** [masterchief4240/MediaMarktBot#1]
Hallo, würdest du das auch für ein paar andere Artikel umschreiben?
Ich biete auch Geld dafür an.

**Comment by masterchief4240** [comment]
Hi, geht es zufällig um die PS5? Dahingehend hab ich schon überlegt, eine Funktion hinzuzufügen. Allerdings muss ich noch schauen, ob genug Interesse besteht.

Bezüglich der Bezahlung, die Software wird immer kostenlos bleiben. Ich werde in Zukunft allerdings einen Donation Link hinzufügen, für freiwillige Unterstützung.

**Comment by LOX311** [comment]
Nein es geht um viele sachen.
Wir RTX CPU oder Mainboards

**Comment by masterchief4240** [comment]
Erstmal habe ich keine Pläne Bots für PC Teile zu erstellen.
