### ISSUE TITLE
Login wait condition funktioniert nicht

### ISSUE THREAD

**Issue by SimonHaenle** [masterchief4240/MediaMarktBot#2]
Leider funktioniert das Programm nicht mehr.
Nach dem Login passiert nichts (er öffnet die eingetragene Webseite nicht) und nach 5 Minuten beendet sich das Programm mit einem Timeout.

**Comment by masterchief4240** [comment]
Hi, hab jetzt seit einigen Monaten nichts mehr an dem Programm gemacht. Wenn Saturn die Website verändert, kommt es zu dem von dir beschrieben Problem. Ich versuche es mir demnächst mal anzuschauen und werde dir hier antworten, sollte es Neuigkeiten geben.

**Comment by masterchief4240** [comment]
Nochmal bitte mit der neuen Version 1.01 probieren.

https://github.com/masterchief4240/MediaMarktBot/releases/tag/v1.01

**Comment by masterchief4240** [comment]
Gerade eben 1.02 released, jetzt sollte es aber wirklich fixed sein. Ansonsten bitte neue Issue aufmachen.

https://github.com/masterchief4240/MediaMarktBot/releases/tag/v1.02
